<?php
/**
 * One-time dev tool: scans views/ for hardcoded Greek UI text and (re)generates
 * database/migrations/042_translation_catalog_seed.sql, seeding translation_keys
 * + translation_values (language_code = 'el') with the extracted strings.
 *
 * Not part of the app runtime — run manually:
 *   php scripts/extract-translation-strings.php
 *
 * Known limitation: text split across nested inline tags (e.g.
 * "<p>Some <strong>bold</strong> text</p>") is extracted as separate
 * fragments ("Some ", " text") rather than one sentence. Acceptable for a
 * first pass — an admin can still translate each fragment.
 *
 * <script>...</script> bodies are blanked out before scanning (same
 * technique as PHP blocks below) so inline JS containing Greek string
 * literals is never mistaken for translatable UI text. An earlier version
 * relied on the ';'-skip filter to catch this instead, which missed
 * semicolon-free JS fragments (e.g. string concatenation with no trailing
 * ';') and let ~13 garbage rows into the seed data — caught in code review.
 */

define('BASE_PATH', dirname(__DIR__));
$viewsDir = BASE_PATH . '/views';
$outFile  = BASE_PATH . '/database/migrations/042_translation_catalog_seed.sql';
$skipLog  = BASE_PATH . '/storage/logs/translation-extraction-skipped.log';

function sqlEscape(string $s): string
{
    return str_replace(["\\", "'"], ["\\\\", "''"], $s);
}

function extractOne(string $text, string $group, array &$seenInFile, int &$index, array &$statements, array &$skipped, int &$total): void
{
    $clean = trim(preg_replace('/\s+/', ' ', $text));
    if ($clean === '' || mb_strlen($clean) < 2) {
        return;
    }
    if (isset($seenInFile[$clean])) {
        return; // duplicate within this file — key already emitted
    }
    if (strpos($clean, ';') !== false) {
        // Migrations may never contain a literal ';' inside a string literal
        // (MigrationRunner splits statements on raw ';'). Skip and log instead.
        $skipped[] = "$group: contains ';' — $clean";
        return;
    }
    $index++;
    $key = $group . '.' . str_pad((string) $index, 3, '0', STR_PAD_LEFT);
    $seenInFile[$clean] = $key;
    $total++;

    $escKey = sqlEscape($key);
    $escGroup = sqlEscape($group);
    $escText = sqlEscape($clean);

    $statements[] = "INSERT INTO translation_keys (str_key, str_group) VALUES ('$escKey', '$escGroup')";
    $statements[] = "INSERT INTO translation_values (key_id, language_code, value) "
        . "SELECT id, 'el', '$escText' FROM translation_keys WHERE str_key = '$escKey'";
}

$files = [];
$rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($viewsDir, FilesystemIterator::SKIP_DOTS));
foreach ($rii as $file) {
    if ($file->isFile() && $file->getExtension() === 'php') {
        $files[] = $file->getPathname();
    }
}
sort($files);

$statements = [];
$skipped = [];
$total = 0;

foreach ($files as $path) {
    $relative = str_replace('\\', '/', substr($path, strlen($viewsDir) + 1));
    $group = preg_replace('/\.php$/', '', $relative);
    $raw = file_get_contents($path);

    // Blank out PHP blocks so PHP code is never mistaken for UI text.
    $withoutPhp = preg_replace_callback('/<\?php.*?\?>|<\?=.*?\?>/s', function ($m) {
        return str_repeat(' ', strlen($m[0]));
    }, $raw);

    // Blank out <script>...</script> bodies so inline JS (which often
    // contains Greek string literals used in dynamic UI text) is never
    // mistaken for a translatable text node.
    $withoutPhp = preg_replace_callback('/<script\b[^>]*>.*?<\/script>/is', function ($m) {
        return str_repeat(' ', strlen($m[0]));
    }, $withoutPhp);

    $seenInFile = [];
    $index = 0;

    // Text nodes: content between > and < containing a Greek character.
    if (preg_match_all('/>([^<>]*[\x{0370}-\x{03FF}\x{1F00}-\x{1FFF}][^<>]*)</u', $withoutPhp, $m)) {
        foreach ($m[1] as $text) {
            extractOne($text, $group, $seenInFile, $index, $statements, $skipped, $total);
        }
    }

    // Attribute values: placeholder / title / alt / aria-label containing Greek.
    if (preg_match_all('/\b(?:placeholder|title|alt|aria-label)="([^"]*[\x{0370}-\x{03FF}\x{1F00}-\x{1FFF}][^"]*)"/u', $withoutPhp, $m)) {
        foreach ($m[1] as $text) {
            extractOne($text, $group, $seenInFile, $index, $statements, $skipped, $total);
        }
    }
}

$header = "-- 042_translation_catalog_seed.sql\n"
    . "-- Auto-generated by scripts/extract-translation-strings.php — DO NOT hand-edit.\n"
    . "-- Seeds translation_keys/translation_values with Greek UI text extracted from views/.\n"
    . "-- Regenerate by re-running the script (it always overwrites this file).\n\n";

file_put_contents($outFile, $header . implode(";\n", $statements) . ";\n");

if ($skipped) {
    file_put_contents($skipLog, implode("\n", $skipped) . "\n");
}

echo "Extracted $total strings from " . count($files) . " views.\n";
echo "Wrote: $outFile\n";
if ($skipped) {
    echo count($skipped) . " strings skipped (contain literal ';') — see $skipLog\n";
}
